#########################################################################
#									#
# File ID: ./.travis.yml						#
# Author: Copyright (C) 2019  Mark Grant				#
#									#
# Released under the GPLv3 only.					#
# SPDX-License-Identifier: GPL-3.0					#
#									#
# Configuration file for Travis CI build tests.				#
#									#
#########################################################################

#########################################################################
#									#
# Changelog								#
#									#
# Date		Author	Version	Description				#
#									#
# 16/06/2019	MG	1.0.1	Initial release.                        #
#									#
#########################################################################


language: c

dist:
    - xenial

before_install:
    - sudo add-apt-repository ppa:m-grant-prg/utils -y
    - sudo apt-get update
    - sudo apt-get install -y autoconf-archive
    - sudo apt-get install -y dia doxygen graphviz txt2man txt2manwrap

script: ./bootstrap.sh -cb

